"""Initial migration

Revision ID: a5d244159d24
Revises: 
Create Date: 2026-06-29 01:05:33.472749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d244159d24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address — globally unique (Section 10.2)"),
    sa.Column('password_hash', sa.Text(), nullable=False, comment='bcrypt hash, cost ≥ 12. Never plaintext (Section 13.4)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Display name'),
    sa.Column('role', sa.String(length=50), nullable=False, comment="System-level role: 'user' or 'admin'"),
    sa.Column('token_version', sa.Integer(), nullable=False, comment='Incremented on global logout to invalidate all issued tokens. Tokens carrying an older version are rejected (Section 13.1).'),
    sa.Column('refresh_token_hash', sa.Text(), nullable=True, comment='bcrypt hash of the current refresh token. Used for rotation + reuse detection (Section 13.1). NULL = no active refresh token.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-disable a user account without deletion'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable project name'),
    sa.Column('project_type', sa.String(length=100), nullable=False, comment="Project category (e.g. 'evaluation', 'automl', 'general')"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='FK to USERS — project creator and owner'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Project this audit log belongs to'),
    sa.Column('actor_id', sa.UUID(), nullable=False, comment='User who performed the action'),
    sa.Column('action', sa.String(length=100), nullable=False, comment="Action performed (e.g. 'project_created', 'member_invited')"),
    sa.Column('target_type', sa.String(length=100), nullable=False, comment="Resource type affected (e.g. 'project', 'member', 'evaluation_run')"),
    sa.Column('target_id', sa.UUID(), nullable=True, comment='UUID of the affected resource'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Additional context (before/after values, relevant IDs, etc.)'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When the action occurred — indexed for chronological retrieval'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_project_id'), 'audit_logs', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Role: viewer | editor | admin | owner (Section 13.2)'),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_members')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_audit_logs_project_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
