"""Baseline schema, generated from the models

Replaces the previous ten-revision chain, which was written for PostgreSQL and
declared every foreign key as postgresql.UUID. On SQLite that yields NUMERIC
affinity, while the models' id columns are CHAR(32) (TEXT affinity), so foreign
keys across the two failed at runtime with "FOREIGN KEY constraint failed".

That chain had never executed on any installation: the migration runner
resolved its repo root one directory too low, found no alembic.ini and returned
silently, so every database was built by Base.metadata.create_all instead - and
a startup hook dropped any table whose DDL contained the word "UUID" to force
create_all's version. Both of those have been removed.

Because no installation ever applied those revisions there is no history to
preserve, so the chain is squashed here. This baseline uses sa.Uuid(), which
renders CHAR(32) on SQLite and native UUID on PostgreSQL, so both dialects get
consistent types. Existing databases already match it and are stamped, not
migrated.

Revision ID: 2107bfe05bb2
Revises:
Create Date: 2026-09-12

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2107bfe05bb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address — globally unique (Section 10.2)"),
    sa.Column('password_hash', sa.Text(), nullable=False, comment='bcrypt hash, cost ≥ 12. Never plaintext (Section 13.4)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Display name'),
    sa.Column('role', sa.String(length=50), nullable=False, comment="System-level role: 'user' or 'admin'"),
    sa.Column('token_version', sa.Integer(), nullable=False, comment='Incremented on global logout to invalidate all issued tokens. Tokens carrying an older version are rejected (Section 13.1).'),
    sa.Column('refresh_token_hash', sa.Text(), nullable=True, comment='bcrypt hash of the current refresh token. Used for rotation + reuse detection (Section 13.1). NULL = no active refresh token.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-disable a user account without deletion'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable project name'),
    sa.Column('project_type', sa.String(length=100), nullable=False, comment="Project category (e.g. 'evaluation', 'automl', 'general')"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False, comment='FK to USERS — project creator and owner'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False, comment='Project this audit log belongs to'),
    sa.Column('actor_id', sa.Uuid(), nullable=False, comment='User who performed the action'),
    sa.Column('action', sa.String(length=100), nullable=False, comment="Action performed (e.g. 'project_created', 'member_invited')"),
    sa.Column('target_type', sa.String(length=100), nullable=False, comment="Resource type affected (e.g. 'project', 'member', 'evaluation_run')"),
    sa.Column('target_id', sa.Uuid(), nullable=True, comment='UUID of the affected resource'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Additional context (before/after values, relevant IDs, etc.)'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When the action occurred — indexed for chronological retrieval'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_project_id'), 'audit_logs', ['project_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_dataset_id'), 'conversations', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_conversations_project_id'), 'conversations', ['project_id'], unique=False)
    op.create_table('datasets',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_name'), 'datasets', ['name'], unique=False)
    op.create_index(op.f('ix_datasets_project_id'), 'datasets', ['project_id'], unique=False)
    op.create_table('golden_datasets',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('baseline_run_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_golden_datasets_name'), 'golden_datasets', ['name'], unique=False)
    op.create_index(op.f('ix_golden_datasets_project_id'), 'golden_datasets', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Role: viewer | editor | admin | owner (Section 13.2)'),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_members')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('provider_credentials',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_credentials_project_id'), 'provider_credentials', ['project_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tools_used', sa.JSON(), nullable=True),
    sa.Column('generated_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('version_tag', sa.String(length=100), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('profile_data', sa.JSON(), nullable=True),
    sa.Column('profile_status', sa.String(length=20), nullable=True),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True),
    sa.Column('transformation_history', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_versions_dataset_id'), 'dataset_versions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_versions_version_tag'), 'dataset_versions', ['version_tag'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('golden_dataset_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('prompt_config_hash', sa.String(length=255), nullable=True),
    sa.Column('scoring_strategy', sa.String(length=30), nullable=True),
    sa.Column('scoring_params', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('aggregate_results', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['golden_dataset_id'], ['golden_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_golden_dataset_id'), 'evaluation_runs', ['golden_dataset_id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('target_column', sa.String(), nullable=False),
    sa.Column('problem_type', sa.String(), nullable=False),
    sa.Column('primary_metric', sa.String(), nullable=False),
    sa.Column('algorithms', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_id'), 'experiments', ['id'], unique=False)
    op.create_table('golden_cases',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('golden_dataset_id', sa.Uuid(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('category_tag', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['golden_dataset_id'], ['golden_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_golden_cases_category_tag'), 'golden_cases', ['category_tag'], unique=False)
    op.create_index(op.f('ix_golden_cases_golden_dataset_id'), 'golden_cases', ['golden_dataset_id'], unique=False)
    op.create_table('scheduled_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('golden_dataset_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['golden_dataset_id'], ['golden_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_evaluations_golden_dataset_id'), 'scheduled_evaluations', ['golden_dataset_id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_run_id', sa.Uuid(), nullable=False),
    sa.Column('golden_case_id', sa.Uuid(), nullable=False),
    sa.Column('actual_output', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scoring_detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['golden_case_id'], ['golden_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_results_evaluation_run_id'), 'evaluation_results', ['evaluation_run_id'], unique=False)
    op.create_index(op.f('ix_evaluation_results_golden_case_id'), 'evaluation_results', ['golden_case_id'], unique=False)
    op.create_table('model_trials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('algorithm_name', sa.String(), nullable=False),
    sa.Column('hyperparameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('primary_metric_score', sa.Float(), nullable=True),
    sa.Column('mlflow_run_id', sa.String(), nullable=True),
    sa.Column('is_best', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_trials_id'), 'model_trials', ['id'], unique=False)
    op.create_table('regression_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_run_id', sa.Uuid(), nullable=False),
    sa.Column('baseline_run_id', sa.Uuid(), nullable=False),
    sa.Column('total_cases', sa.Integer(), nullable=False),
    sa.Column('regressed_cases', sa.Integer(), nullable=False),
    sa.Column('newly_passing_cases', sa.Integer(), nullable=False),
    sa.Column('stable_cases', sa.Integer(), nullable=False),
    sa.Column('critical_regressions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_run_id')
    )
    op.create_table('regression_report_cases',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('golden_case_id', sa.Uuid(), nullable=False),
    sa.Column('category_tag', sa.String(length=100), nullable=True),
    sa.Column('status_transition', sa.String(length=50), nullable=False),
    sa.Column('baseline_score', sa.Float(), nullable=True),
    sa.Column('new_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['golden_case_id'], ['golden_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['regression_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regression_report_cases_report_id'), 'regression_report_cases', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regression_report_cases_report_id'), table_name='regression_report_cases')
    op.drop_table('regression_report_cases')
    op.drop_table('regression_reports')
    op.drop_index(op.f('ix_model_trials_id'), table_name='model_trials')
    op.drop_table('model_trials')
    op.drop_index(op.f('ix_evaluation_results_golden_case_id'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_evaluation_run_id'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_scheduled_evaluations_golden_dataset_id'), table_name='scheduled_evaluations')
    op.drop_table('scheduled_evaluations')
    op.drop_index(op.f('ix_golden_cases_golden_dataset_id'), table_name='golden_cases')
    op.drop_index(op.f('ix_golden_cases_category_tag'), table_name='golden_cases')
    op.drop_table('golden_cases')
    op.drop_index(op.f('ix_experiments_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_evaluation_runs_golden_dataset_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_dataset_versions_version_tag'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_dataset_id'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_provider_credentials_project_id'), table_name='provider_credentials')
    op.drop_table('provider_credentials')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_golden_datasets_project_id'), table_name='golden_datasets')
    op.drop_index(op.f('ix_golden_datasets_name'), table_name='golden_datasets')
    op.drop_table('golden_datasets')
    op.drop_index(op.f('ix_datasets_project_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_name'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_conversations_project_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_dataset_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_logs_project_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
